<a href="https://colab.research.google.com/github/PRIYARANJAN-SYS/PRIYARANJAN-SYS/blob/main/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
#the array object in numpy is known as ndarray
#array is used where speed and resources are very important


In [2]:
#installing numpy library
!pip install numpy

In [7]:
#import numpy
import numpy as np


In [4]:
arr=np.arr([1,2,3,4,5])
print(arr)

[1 2 3 4 5]


In [5]:
type(arr)

numpy.ndarray

In [10]:
#0-D array
arr=np.array(42)
print(arr)
type(arr)

42


numpy.ndarray

In [21]:
#1-D array
arr1=np.array([1,2,3,4,5])
print(arr1)

[1 2 3 4 5]


In [18]:
#2-D array
arr2=np.array([[1,2,3],[4,5,6]])
print(arr2)

[[1 2 3]
 [4 5 6]]


In [19]:
# 3-D array
arr3=np.array([[[1,2,3],[4,4,5],[7,7,8],[8,7,6]]])
print(arr3)

[[[1 2 3]
  [4 4 5]
  [7 7 8]
  [8 7 6]]]


In [23]:
#to find the dimension of the array
print(arr1.ndim)
print(arr2.ndim)
print(arr3.ndim)

1
2
3


In [27]:
arr4=np.array([1,2,3,4],ndmin=5)
print(arr4)
print("number of dimension",arr4.ndim)

[[[[[1 2 3 4]]]]]
number of dimension 5


In [28]:
arr1=np.array([1,2,3,4,5])
print(arr1[0])

1


In [30]:
arr2=np.array([[[1,2,3,4,5],[2,3,4,5,6],[6,5,4,3,3]]])
print(arr2[[0]])

[[[1 2 3 4 5]
  [2 3 4 5 6]
  [6 5 4 3 3]]]


In [31]:
arr3=([[1,2,3],[4,5,6]],[[2,3,4],[5,6,7]])
print(arr3[0])

[[1, 2, 3], [4, 5, 6]]


In [32]:
arr1=np.array([1,2,3,4,5])
print(arr1[2:5])

[3 4 5]
